// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using creaturegame.DB;

#nullable disable

namespace creaturegame.DB.Migrations.Items
{
    [DbContext(typeof(ItemsDbContext))]
    partial class ItemsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("creaturegame.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CuredStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CuresAllStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlingPower")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HealAmount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HealsAllHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PpRestoreAmount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RestoresAllPp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RevivePercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpriteUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatBoostStages")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatBoostStat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
