// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using creaturegame.DB;

#nullable disable

namespace creaturegame.DB.Migrations.Moves
{
    [DbContext(typeof(MovesDbContext))]
    [Migration("20260527180511_AddStatEffectAndMoveEffect")]
    partial class AddStatEffectAndMoveEffect
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("creaturegame.Attacks.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Effect")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EffectChance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHighCrit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerPointsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatEffectChance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatEffectDelta")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatEffectStat")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatEffectTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusEffect")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
