// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using creaturegame.DB;

#nullable disable

namespace creaturegame.DB.Migrations.Pokemon
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20260618200916_AddPokemonEvolution")]
    partial class AddPokemonEvolution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("creaturegame.DB.PokemonEvolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromSpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LevelThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StoneItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToSpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromSpeciesId", "Generation");

                    b.HasIndex("FromSpeciesId", "ToSpeciesId", "Generation")
                        .IsUnique();

                    b.ToTable("PokemonEvolution", (string)null);
                });

            modelBuilder.Entity("creaturegame.DB.PokemonGameAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailabilityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId", "GameVersion")
                        .IsUnique();

                    b.ToTable("PokemonGameAvailability", (string)null);
                });

            modelBuilder.Entity("creaturegame.DB.PokemonLearnset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LearnLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId", "Generation", "LearnLevel");

                    b.ToTable("PokemonLearnset", (string)null);
                });

            modelBuilder.Entity("creaturegame.DB.PokemonSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseExperience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseHP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpecial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatchRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrowthRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PokedexEntry")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type2")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PokemonSpecies", (string)null);
                });

            modelBuilder.Entity("creaturegame.DB.PokemonEvolution", b =>
                {
                    b.HasOne("creaturegame.DB.PokemonSpecies", null)
                        .WithMany()
                        .HasForeignKey("FromSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("creaturegame.DB.PokemonGameAvailability", b =>
                {
                    b.HasOne("creaturegame.DB.PokemonSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("creaturegame.DB.PokemonLearnset", b =>
                {
                    b.HasOne("creaturegame.DB.PokemonSpecies", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
